# Generated by Django 5.2.7 on 2025-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('name', 'tenant_schema')},
        ),
    ]
