# Generated by Django 5.2.6 on 2025-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_tenant_schema_eventtype_tenant_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the event is active and visible to users'),
        ),
    ]
