# Generated by Django 5.2.6 on 2025-10-06 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
    ]
