# Generated by Django 5.2.7 on 2025-10-04 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('events', '0002_event_tenant_schema_eventtype_tenant_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='tenant_schema',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('event', 'user', 'tenant_schema')},
        ),
    ]
