# Generated by Django 5.2.6 on 2025-10-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0003_alter_booking_unique_together_booking_tenant_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant'),
        ),
    ]
